name: actions-tutorial
on: [push]
jobs:
        check-bats-version:
                runs-on: ubuntu-latest
                steps:
                        - run: |
                                cd ..
                                cd ..
                                ls
                                bash  check_gcd_script.sh
